### ISSUE TITLE
Изменения на странице добавления анкеты претендента

### ISSUE THREAD

**Issue by spartaksun** [czvl/portal#19]
Страница http://czvl.org.ua/applicants
1. После заполнения даты рождения -  убрать календарь - заменить на маску ввода.
2. Поле "Досвід роботи"  - добавить описание в название поля:
   Досвід роботи - заклад в якому працювали, посада, період.
3. Поле "Навички" -  добавить описание в названии поля:
   Навички, вміння (Приклади. Для секретаря: планування робочого дня керівника, робота з гугл доками, організація прийомів, нарад тощо. Для продавця: комунікативні навички, оріентуватись в товарі, вміння задавати правильні питання, навички активного слухання тощо. Для електрика: створення плану розміщення електропроводки, вміння розрахувати потрібний розмір кабелю, підключати будь яке електрообладнання тощо)
4. Добавить поле "Бажана посада" - добавить список должностей.
5. Поле "Електронна пошта" -  добавить текстовое предупреждение, чтобы перепроверяли правильность телефона и почты, так как иначе мы не сможем с ним связаться (кандидаты допускают ошибки)
6. Поле "Інші контакти" - название поля изменить на ""Інші контакти (якщо є ще один телефон або пошта, скайп, соціальні мережі)"""
7. Поле "Про себе" -     переименовать на "Додаткова інформація" +     Наяність інвалідності (вкажіть, будь ласка, групу) .
8. Добавить текстовое поле "Наяність інвалідності (вкажіть, будь ласка, групу)"

**Comment by olgasemenova** [comment]
Contributor :  asopin
