### ISSUE TITLE
Функционал "Знание иностранных языков"

### ISSUE THREAD

**Issue by spartaksun** [czvl/portal#20]
В анкету http://czvl.org.ua/applicants Добавить поле "Знання іноземних мов" .
Выпадающий список из значений + выбор более одного языка.

Реализовать ф-л ввода и редактирования иностранных языков в анкете соискателя.

(Список на основные языки - английский, немецкий, французкий +інші.) Рівень володіння іноземними мовами - А1 - початковий рівень, А2 - знання основ, В1 - середній рівень, В2 - вище середнього, С1 - просунутий, С2 - досвідчений;   Добавить поле. Выпадающий список из значений + выбор более одного языка.

**Comment by olgasemenova** [comment]
Contributor :
