### ISSUE TITLE
Ошибка базы при редактировании полей

### ISSUE THREAD

**Issue by olgasemenova** [czvl/portal#40]
При работе с базой, полями "Бажана посада" и "Можлива посада" возникает ошибка.
Ошибка возникает если выбран фильм в обеих полях.
 (see attach)
![bug](https://cloud.githubusercontent.com/assets/16706049/12795672/bc30aa20-cac3-11e5-942d-58d59a361690.png)

**Comment by olgasemenova** [comment]
@asopin

**Comment by asopin** [comment]
attaching a log example
[czvl_40_log.txt](https://github.com/czvl/portal/files/117122/czvl_40_log.txt)

Steps to reproduce:
1. Navigate to http://czvl.org.ua/manage/profiles/index
2. Select both filters "Бажана посада" and "Можлива посада"
3. Click on "Знайти" button
