### ISSUE TITLE
Поиск анкет по комментариям волонтеров-ректуреров

### ISSUE THREAD

**Issue by olgasemenova** [czvl/portal#59]
Добавить возможность поиск анкет по параметру - комментарии/действия волонтеров

Таким образом, волонтер сможет находить все анкеты, с которыми он работал и в которых оставлял комментарий в разделе "Статус" и/или в которых отмечен как "Рекрутер"
![default](https://cloud.githubusercontent.com/assets/16706049/15466925/8b844dd8-20e4-11e6-89e9-292ad5a45acf.png)

**Comment by kotaba** [comment]
взял

**Comment by kotaba** [comment]
#60 #61

**Comment by olgasemenova** [comment]
done
