### ISSUE TITLE
Уведомление волонтеру-рекрутеру о действиях по кандидату

### ISSUE THREAD

**Issue by olgasemenova** [czvl/portal#63]
Сделать уведомление на почту Рекрутеру (указан в анкете кандидата) о том, что по его кандидату появился новый статус или комментарий.
При этом уведомления приходят только о действиях других пользователей, а не его самого.

**Comment by kotaba** [comment]
+

**Comment by olgasemenova** [comment]
updated issue

**Comment by kotaba** [comment]
completed

**Comment by marinalebed** [comment]
Это божественно)
26 черв. 2016 14:21 "Olga" notifications@github.com пише:
